const LLM_QUALITY_MEDIUM = 'medium';
const LLM_QUALITY_HIGH = 'high';

const LLM_CREATIVITY_NONE = 'none';
const LLM_CREATIVITY_LOW = 'low';
const LLM_CREATIVITY_MEDIUM = 'medium';
const LLM_CREATIVITY_HIGH = 'high';

const RESID_PREFIX_AGENT = 'agnt-';
const RESID_PREFIX_TURN = 'turn-';
const RESID_PREFIX_CONNECTOR = 'conn-';
const RESID_PREFIX_CONVERSATION = 'conv-';
const RESID_PREFIX_CONVERSATION_DOCUMENT = 'doc-conv-';
const RESID_PREFIX_DATASOURCE = 'dsrc-';
const RESID_PREFIX_DOCUMENT = 'doc-';

module.exports = {
  LLM_QUALITY_MEDIUM,
  LLM_QUALITY_HIGH,

  LLM_CREATIVITY_NONE,
  LLM_CREATIVITY_LOW,
  LLM_CREATIVITY_MEDIUM,
  LLM_CREATIVITY_HIGH,

  RESID_PREFIX_AGENT,
  RESID_PREFIX_TURN,
  RESID_PREFIX_CONNECTOR,
  RESID_PREFIX_CONVERSATION,
  RESID_PREFIX_CONVERSATION_DOCUMENT,
  RESID_PREFIX_DATASOURCE,
  RESID_PREFIX_DOCUMENT,
};
